### ISSUE TITLE
Persisting cluster members crashes when previous members can't be found

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happner-cluster#166]
Persisting members was implemented for the bug that non-seed members did not rejoin the cluster once a certain time had expired.

Now, if a persisted member is not present, the seed member crashes.

**Comment by southbite** [comment]
Not the case I think - the crash as logged looks like a protocol layer issue, which must be fixed in happn-3, changing this issue now to reflect that.

**Comment by southbite** [comment]
2019-04-11 09:06:27.839 [ INFO] - 1546ms	10-0-28-181_57000 (Orchestrator) cluster size 3 (happner-elastic-feed arrived)
2019-04-11 09:06:27.839 [ INFO] - 0ms	(Happn) '_ADMIN' connected
2019-04-11 09:06:27.848 [ INFO] - 9ms	(HappnerClient) dependent session-manager has 1 of historianStore ^5.0.0
2019-04-11 09:06:27.848 [ INFO] - 0ms	(HappnerClient) dependent historian-api has 1 of historianStore ^5.0.0
2019-04-11 09:06:27.848 [ INFO] - 0ms	(HappnerClient) dependent fieldpop-api has 1 of historianStore ^5.0.0
2019-04-11 09:06:27.849 [ INFO] - 1ms	(HappnerClient) dependent webhooks has 1 of historianStore ^5.0.0
2019-04-11 09:06:27.849 [ INFO] - 0ms	(HappnerClient) dependent liveDataServer has 1 of historianStore ^5.0.0
2019-04-11 09:06:27.849 [ INFO] - 0ms	(HappnerClient) dependent liveDataServer has 1 of proxy *
2019-04-11 09:06:29.160 [ERROR] - 1311ms	10-0-28-181_57000 (HappnServer) : TypeCannot read property 'transformSystem' of undefined, severity: 0 system error: ProtocolService, stack: TypeError: Cannot read property 'transformSystem' of undefined
    at ProtocolService.processSystemOut (/home/ubuntu/field-pop/node_modules/happn-3/lib/services/protocol/service.js:47:71)
    at /home/ubuntu/field-pop/node_modules/happn-3/lib/services/session/service.js:439:39
    at /home/ubuntu/field-pop/node_modules/happn-3/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/async/lib/async.js:209:22)
    at /home/ubuntu/field-pop/node_modules/happn-3/lib/services/session/service.js:435:11
    at tryCatcher (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/promise.js:70:37)
    at SessionService.securityDirectoryChanged (/home/ubuntu/field-pop/node_modules/happn-3/lib/services/session/service.js:431:10)
    at Promise (/home/ubuntu/field-pop/node_modules/happn-3/lib/services/security/service.js:1027:39)
    at tryCatcher (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/promise.js:70:37)
    at users.clearCaches.then.then.then.then.then.effectedSessions (/home/ubuntu/field-pop/node_modules/happn-3/lib/services/security/service.js:1024:14)
    at tryCatcher (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/ubuntu/field-pop/node_modules/happn-3/node_modules/bluebird/js/main/async.js:15:14)
    at Immediate.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.15.0/lib/node_modules/pm2/node_modules/async-listener/glue.js:188:31)
    at Immediate.args.(anonymous function) [as _onImmediate] (/home/ubuntu/.nvm/versions/node/v10.15.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
2019-04-11 09:06:29.163 [FATAL] - 3ms	10-0-28-181_57000 (HappnServer) fatal error { [SystemError: TypeError: Cannot read property 'transformSystem' of undefined]
  message:
   'TypeError: Cannot read property \'transformSystem\' of undefined',
  name: 'SystemError',
  code: 500,
  severity: 0 }
2019-04-11 09:06:29.171 [ INFO] - 8ms	(Mesh) exit 1

**Comment by southbite** [comment]
Fixed with new happn release: happner/happn-3#199
